version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.2.0
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
